"""
Erweiterter DACH Tourism Seed
Ziel: alle Unternehmen die Call Center Support benötigen könnten
Größe: 50-2000 MA, Umsatz ab ~5 Mio €
Quellen: Branchenkenntnis, öffentliche Verzeichnisse, Verbandslisten
"""

EXTENDED_COMPANIES = [

    # ═══ AIRLINES & CHARTER ═══
    {"name": "Condor Flugdienst GmbH", "category": "airline", "country": "DE", "city": "Frankfurt", "website": "https://www.condor.com", "email_general": "info@condor.com", "phone_main": "+49 6107 9394522", "size": "large", "employees_approx": 4900, "revenue_approx_eur": 1500000000},
    {"name": "SunExpress Deutschland GmbH", "category": "airline", "country": "DE", "city": "Nuremberg", "website": "https://www.sunexpress.com", "email_general": "info@sunexpress.com", "phone_main": "+49 911 9418200", "size": "medium", "employees_approx": 850},
    {"name": "Wizz Air Germany", "category": "airline", "country": "DE", "city": "Berlin", "website": "https://wizzair.com", "size": "large", "employees_approx": 1200},
    {"name": "Corendon Airlines", "category": "airline", "country": "DE", "city": "Düsseldorf", "website": "https://www.corendonairlines.com", "size": "medium", "employees_approx": 600},
    {"name": "Germania Fluggesellschaft mbH", "category": "airline", "country": "DE", "city": "Berlin", "website": "https://www.flygermania.com", "size": "medium", "employees_approx": 500},
    {"name": "Luxair S.A.", "category": "airline", "country": "DE", "city": "Luxemburg", "website": "https://www.luxair.lu", "size": "medium", "employees_approx": 2600},
    {"name": "Air Dolomiti S.p.A.", "category": "airline", "country": "DE", "city": "Verona", "website": "https://www.airdolomiti.eu", "size": "medium", "employees_approx": 450},
    {"name": "Lauda Europe", "category": "airline", "country": "AT", "city": "Wien", "website": "https://www.laudamotion.com", "size": "medium", "employees_approx": 700},
    {"name": "People's Viennaline", "category": "airline", "country": "AT", "city": "Wien", "website": "https://www.viennaline.at", "size": "small", "employees_approx": 120},
    {"name": "Edelweiss Air AG", "category": "airline", "country": "CH", "city": "Zürich", "website": "https://www.flyedelweiss.com", "size": "medium", "employees_approx": 750},
    {"name": "Helvetic Airways AG", "category": "airline", "country": "CH", "city": "Zürich", "website": "https://www.helvetic.com", "size": "small", "employees_approx": 380},
    {"name": "Chair Airlines AG", "category": "airline", "country": "CH", "city": "Zürich", "website": "https://www.chairairlines.com", "size": "small", "employees_approx": 200},

    # ═══ KREUZFAHRT ═══
    {"name": "A-ROSA Flussschiff GmbH", "category": "kreuzfahrt", "country": "DE", "city": "Rostock", "website": "https://www.a-rosa.de", "email_general": "info@a-rosa.de", "phone_main": "+49 381 2026-4500", "size": "medium", "employees_approx": 700, "revenue_approx_eur": 280000000},
    {"name": "Viking River Cruises Germany", "category": "kreuzfahrt", "country": "DE", "city": "München", "website": "https://www.vikingrivercruises.de", "size": "medium", "employees_approx": 400},
    {"name": "Kreuzfahrten.de GmbH", "category": "kreuzfahrt", "country": "DE", "city": "Hamburg", "website": "https://www.kreuzfahrten.de", "size": "small", "employees_approx": 80},
    {"name": "Plantours & Partner GmbH", "category": "kreuzfahrt", "country": "DE", "city": "Bremen", "website": "https://www.plantours-partner.de", "size": "small", "employees_approx": 65},
    {"name": "Arosa Flusskreuzfahrten", "category": "kreuzfahrt", "country": "CH", "city": "Chur", "website": "https://www.arosa-cruises.ch", "size": "small", "employees_approx": 150},
    {"name": "Lüftner Cruises GmbH", "category": "kreuzfahrt", "country": "AT", "city": "Innsbruck", "website": "https://www.luftner-cruises.com", "size": "small", "employees_approx": 90},
    {"name": "Crystal Cruises Germany", "category": "kreuzfahrt", "country": "DE", "city": "Hamburg", "website": "https://www.crystalcruises.de", "size": "medium", "employees_approx": 200},
    {"name": "Windstar Cruises Germany", "category": "kreuzfahrt", "country": "DE", "city": "Hamburg", "website": "https://www.windstarcruises.de", "size": "small", "employees_approx": 75},
    {"name": "Silversea Cruises Germany", "category": "kreuzfahrt", "country": "DE", "city": "Hamburg", "website": "https://www.silversea.com", "size": "medium", "employees_approx": 250},
    {"name": "Regent Seven Seas Germany", "category": "kreuzfahrt", "country": "DE", "city": "Hamburg", "website": "https://www.rssc.com", "size": "medium", "employees_approx": 180},

    # ═══ REISEVERANSTALTER ═══
    {"name": "Schauinsland-Reisen GmbH", "category": "veranstalter", "country": "DE", "city": "Duisburg", "website": "https://www.schauinsland-reisen.de", "email_general": "info@schauinsland-reisen.de", "phone_main": "+49 203 7676-0", "size": "medium", "employees_approx": 400, "revenue_approx_eur": 650000000},
    {"name": "Dertour GmbH & Co. KG", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.dertour.de", "phone_main": "+49 69 9588-2000", "size": "large", "employees_approx": 3000, "revenue_approx_eur": 2800000000},
    {"name": "REWE Reisen", "category": "veranstalter", "country": "DE", "city": "Köln", "website": "https://www.rewe-reisen.de", "size": "large", "employees_approx": 1200},
    {"name": "Lidl Reisen GmbH", "category": "veranstalter", "country": "DE", "city": "Neckarsulm", "website": "https://www.lidl-reisen.de", "size": "medium", "employees_approx": 300},
    {"name": "Meiers Weltreisen GmbH", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.meiersweltreisen.de", "phone_main": "+49 69 66428-666", "size": "medium", "employees_approx": 350, "revenue_approx_eur": 280000000},
    {"name": "Tjaereborg Reisen GmbH", "category": "veranstalter", "country": "DE", "city": "Hamburg", "website": "https://www.tjaereborg.de", "size": "medium", "employees_approx": 180},
    {"name": "Öger Tours GmbH", "category": "veranstalter", "country": "DE", "city": "Hamburg", "website": "https://www.oeger.de", "phone_main": "+49 40 30 30 90", "size": "medium", "employees_approx": 250, "revenue_approx_eur": 350000000},
    {"name": "Eberhardt Travel GmbH", "category": "veranstalter", "country": "DE", "city": "Dresden", "website": "https://www.eberhardt-travel.de", "size": "small", "employees_approx": 120},
    {"name": "Falk Reisen GmbH", "category": "veranstalter", "country": "DE", "city": "Nürnberg", "website": "https://www.falk-reisen.de", "size": "small", "employees_approx": 90},
    {"name": "Euvia Travel GmbH", "category": "veranstalter", "country": "DE", "city": "Hamburg", "website": "https://www.5vorflug.de", "size": "medium", "employees_approx": 220},
    {"name": "Travelhouse GmbH", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.travelhouse.de", "size": "small", "employees_approx": 110},
    {"name": "Coral Travel Germany", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.coraltravel.de", "size": "medium", "employees_approx": 160},
    {"name": "Primasol Hotels & Resorts", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.primasol.de", "size": "medium", "employees_approx": 200},
    {"name": "Helvetic Tours AG", "category": "veranstalter", "country": "CH", "city": "Zürich", "website": "https://www.helvetic-tours.ch", "size": "medium", "employees_approx": 180, "revenue_approx_eur": 320000000},
    {"name": "Kuoni Travel AG", "category": "veranstalter", "country": "CH", "city": "Zürich", "website": "https://www.kuoni.ch", "phone_main": "+41 44 277 44 44", "size": "large", "employees_approx": 2100, "revenue_approx_eur": 1200000000},
    {"name": "Hotelplan Suisse", "category": "veranstalter", "country": "CH", "city": "Glattbrugg", "website": "https://www.hotelplan.ch", "size": "medium", "employees_approx": 600, "revenue_approx_eur": 800000000},
    {"name": "TUI Suisse AG", "category": "veranstalter", "country": "CH", "city": "Zürich", "website": "https://www.tui.ch", "size": "medium", "employees_approx": 280},
    {"name": "KNECHT Reisen AG", "category": "veranstalter", "country": "CH", "city": "Windisch", "website": "https://www.knecht-reisen.ch", "size": "small", "employees_approx": 130},
    {"name": "ITS Coop Travel", "category": "veranstalter", "country": "CH", "city": "Basel", "website": "https://www.its-coop.ch", "size": "medium", "employees_approx": 240},
    {"name": "Neckermann Reisen AT", "category": "veranstalter", "country": "AT", "city": "Wien", "website": "https://www.neckermann.at", "size": "medium", "employees_approx": 200},
    {"name": "Eurotours GmbH", "category": "veranstalter", "country": "AT", "city": "Kirchberg", "website": "https://www.eurotours.at", "phone_main": "+43 5357 5100", "size": "medium", "employees_approx": 350, "revenue_approx_eur": 420000000},
    {"name": "Jahn Reisen AT", "category": "veranstalter", "country": "AT", "city": "Wien", "website": "https://www.jahnreisen.at", "size": "medium", "employees_approx": 180},
    {"name": "Touroperator.at GmbH", "category": "veranstalter", "country": "AT", "city": "Wien", "website": "https://www.touroperator.at", "size": "small", "employees_approx": 75},
    {"name": "Gulet Touroperator GmbH", "category": "veranstalter", "country": "AT", "city": "Wien", "website": "https://www.gulet.at", "size": "small", "employees_approx": 60},
    {"name": "Pegasus Touristik GmbH", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.pegasus.de", "size": "medium", "employees_approx": 140},
    {"name": "Airtours International GmbH", "category": "veranstalter", "country": "DE", "city": "Hamburg", "website": "https://www.airtours.de", "size": "medium", "employees_approx": 320, "revenue_approx_eur": 480000000},
    {"name": "Rewe Touristik GmbH", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.rewe-touristik.de", "size": "large", "employees_approx": 2800},
    {"name": "Bucher Reisen GmbH", "category": "veranstalter", "country": "DE", "city": "Nürnberg", "website": "https://www.bucher-reisen.de", "phone_main": "+49 911 9055-0", "size": "medium", "employees_approx": 280, "revenue_approx_eur": 220000000},
    {"name": "BigXtra Touristik GmbH", "category": "veranstalter", "country": "DE", "city": "München", "website": "https://www.bigxtra.de", "size": "medium", "employees_approx": 190},
    {"name": "Idealtours GmbH", "category": "veranstalter", "country": "DE", "city": "München", "website": "https://www.idealtours.de", "size": "small", "employees_approx": 95},
    {"name": "Travelscout24 GmbH", "category": "veranstalter", "country": "DE", "city": "München", "website": "https://www.travelscout24.de", "size": "medium", "employees_approx": 160},
    {"name": "Transavia Tours GmbH", "category": "veranstalter", "country": "DE", "city": "Düsseldorf", "website": "https://www.transavia.com", "size": "medium", "employees_approx": 120},
    {"name": "Kras Travel GmbH", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.kras.de", "size": "small", "employees_approx": 70},
    {"name": "Terramar Travel GmbH", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.terramar.de", "size": "small", "employees_approx": 85},
    {"name": "Marmara Deutschland GmbH", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.marmara.com", "size": "small", "employees_approx": 65},
    {"name": "Solaris Touristik GmbH", "category": "veranstalter", "country": "DE", "city": "Hamburg", "website": "https://www.solaris.de", "size": "small", "employees_approx": 55},
    {"name": "Ameropa Reisen GmbH", "category": "veranstalter", "country": "DE", "city": "Bad Homburg", "website": "https://www.ameropa.de", "phone_main": "+49 6172 9525-0", "size": "medium", "employees_approx": 250, "revenue_approx_eur": 180000000},
    {"name": "Nazar Nordic GmbH", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.nazar.de", "size": "medium", "employees_approx": 170},
    {"name": "Aldiana GmbH", "category": "veranstalter", "country": "DE", "city": "Frankfurt", "website": "https://www.aldiana.de", "phone_main": "+49 69 7566-0", "size": "medium", "employees_approx": 2200, "revenue_approx_eur": 290000000},
    {"name": "Club Med Germany GmbH", "category": "veranstalter", "country": "DE", "city": "München", "website": "https://www.clubmed.de", "size": "medium", "employees_approx": 180},
    {"name": "Robinson Club GmbH", "category": "veranstalter", "country": "DE", "city": "Hannover", "website": "https://www.robinson.com", "phone_main": "+49 511 567-3000", "size": "large", "employees_approx": 3500, "revenue_approx_eur": 380000000},

    # ═══ OTA / ONLINE PORTALE ═══
    {"name": "Expedia Group Germany", "category": "ota", "country": "DE", "city": "Berlin", "website": "https://www.expedia.de", "size": "enterprise", "employees_approx": 800},
    {"name": "Trivago GmbH", "category": "ota", "country": "DE", "city": "Düsseldorf", "website": "https://www.trivago.de", "phone_main": "+49 211 3812600", "size": "large", "employees_approx": 1200, "revenue_approx_eur": 430000000},
    {"name": "Airbnb Germany GmbH", "category": "ota", "country": "DE", "city": "Hamburg", "website": "https://www.airbnb.de", "size": "large", "employees_approx": 350},
    {"name": "GetYourGuide Deutschland GmbH", "category": "ota", "country": "DE", "city": "Berlin", "website": "https://www.getyourguide.de", "phone_main": "+49 30 2300 9610", "size": "large", "employees_approx": 800, "revenue_approx_eur": 200000000},
    {"name": "Urlaubspiraten GmbH", "category": "ota", "country": "DE", "city": "Berlin", "website": "https://www.urlaubspiraten.de", "size": "medium", "employees_approx": 120},
    {"name": "Ab-in-den-Urlaub GmbH", "category": "ota", "country": "DE", "city": "Berlin", "website": "https://www.ab-in-den-urlaub.de", "size": "medium", "employees_approx": 200, "revenue_approx_eur": 180000000},
    {"name": "Fluege.de GmbH", "category": "ota", "country": "DE", "city": "Hamburg", "website": "https://www.fluege.de", "size": "medium", "employees_approx": 150},
    {"name": "Idealo Internet GmbH (Reisen)", "category": "ota", "country": "DE", "city": "Berlin", "website": "https://www.idealo.de/reisen", "size": "large", "employees_approx": 800},
    {"name": "Opodo GmbH", "category": "ota", "country": "DE", "city": "Berlin", "website": "https://www.opodo.de", "size": "medium", "employees_approx": 300},
    {"name": "eDreams Germany GmbH", "category": "ota", "country": "DE", "city": "Frankfurt", "website": "https://www.edreams.de", "size": "medium", "employees_approx": 180},
    {"name": "Kayak Germany GmbH", "category": "ota", "country": "DE", "city": "Berlin", "website": "https://www.kayak.de", "size": "medium", "employees_approx": 160},
    {"name": "Tourlane GmbH", "category": "ota", "country": "DE", "city": "Berlin", "website": "https://www.tourlane.de", "size": "medium", "employees_approx": 200},
    {"name": "Dreamlines GmbH", "category": "ota", "country": "DE", "city": "Hamburg", "website": "https://www.dreamlines.de", "phone_main": "+49 40 300 30 83 00", "size": "medium", "employees_approx": 280, "revenue_approx_eur": 150000000},
    {"name": "Kreuzfahrtwelt GmbH", "category": "ota", "country": "DE", "city": "Hamburg", "website": "https://www.kreuzfahrtwelt.de", "size": "small", "employees_approx": 70},
    {"name": "Holidaycheck AG", "category": "ota", "country": "DE", "city": "Holzkirchen", "website": "https://www.holidaycheck.de", "phone_main": "+49 8024 999-0", "size": "medium", "employees_approx": 350, "revenue_approx_eur": 90000000},
    {"name": "Reise.de GmbH", "category": "ota", "country": "DE", "city": "Hamburg", "website": "https://www.reise.de", "size": "small", "employees_approx": 80},
    {"name": "Thomas Cook Touristik GmbH", "category": "ota", "country": "DE", "city": "Oberursel", "website": "https://www.thomascook.de", "size": "medium", "employees_approx": 500},
    {"name": "Booking.com Germany", "category": "ota", "country": "DE", "city": "Amsterdam", "website": "https://www.booking.com", "size": "enterprise", "employees_approx": 600},
    {"name": "Hotels.com Germany", "category": "ota", "country": "DE", "city": "Berlin", "website": "https://www.hotels.com", "size": "medium", "employees_approx": 200},

    # ═══ REISEBÜROS / VERMITTLER (Ketten) ═══
    {"name": "REWE Reisebüro GmbH", "category": "vermittler", "country": "DE", "city": "Köln", "website": "https://www.rewe-reisebuero.de", "size": "large", "employees_approx": 2000},
    {"name": "Hapag-Lloyd Reisebüro GmbH", "category": "vermittler", "country": "DE", "city": "Hamburg", "website": "https://www.hlx.com", "size": "medium", "employees_approx": 400},
    {"name": "TUI ReiseCenter", "category": "vermittler", "country": "DE", "city": "Hannover", "website": "https://www.tui-reisecenter.de", "size": "large", "employees_approx": 3000},
    {"name": "DER Reisebüro GmbH", "category": "vermittler", "country": "DE", "city": "Frankfurt", "website": "https://www.der.de", "phone_main": "+49 69 9588-0", "size": "large", "employees_approx": 4000, "revenue_approx_eur": 800000000},
    {"name": "Thomas Cook Reisebüro", "category": "vermittler", "country": "DE", "city": "Oberursel", "website": "https://www.thomascook.de", "size": "large", "employees_approx": 1800},
    {"name": "Neckermann Reisebüro", "category": "vermittler", "country": "DE", "city": "Frankfurt", "website": "https://www.neckermann.de", "size": "large", "employees_approx": 1200},
    {"name": "ADAC Reise GmbH", "category": "vermittler", "country": "DE", "city": "München", "website": "https://www.adac-reise.de", "phone_main": "+49 89 7676-7676", "size": "large", "employees_approx": 800, "revenue_approx_eur": 650000000},
    {"name": "Alltours Reisebüro GmbH", "category": "vermittler", "country": "DE", "city": "Düsseldorf", "website": "https://www.alltours.de", "size": "medium", "employees_approx": 600},
    {"name": "Travel House Media GmbH", "category": "vermittler", "country": "DE", "city": "Düsseldorf", "website": "https://www.travelhouse.de", "size": "medium", "employees_approx": 200},
    {"name": "Reiseland GmbH", "category": "vermittler", "country": "DE", "city": "Hannover", "website": "https://www.reiseland.de", "size": "medium", "employees_approx": 350},
    {"name": "Globetrotter Ausrüstung GmbH (Reisen)", "category": "vermittler", "country": "DE", "city": "Hamburg", "website": "https://www.globetrotter.de", "size": "medium", "employees_approx": 900},
    {"name": "Ameropa Reisebüro", "category": "vermittler", "country": "DE", "city": "Bad Homburg", "website": "https://www.ameropa.de", "size": "medium", "employees_approx": 180},
    {"name": "Fischer Reisen GmbH", "category": "vermittler", "country": "AT", "city": "Wien", "website": "https://www.fischerreisen.at", "phone_main": "+43 1 53 000-0", "size": "large", "employees_approx": 1200, "revenue_approx_eur": 580000000},
    {"name": "Verkehrsbüro Ruefa GmbH", "category": "vermittler", "country": "AT", "city": "Wien", "website": "https://www.ruefa.at", "size": "medium", "employees_approx": 600},
    {"name": "Öamtc Reisebüro", "category": "vermittler", "country": "AT", "city": "Wien", "website": "https://www.oeamtc.at/reise", "size": "medium", "employees_approx": 280},
    {"name": "Raiffeisen Reisen GmbH", "category": "vermittler", "country": "AT", "city": "Wien", "website": "https://www.raiffeisen-reisen.at", "size": "medium", "employees_approx": 200},
    {"name": "TUI ReiseCenter AT", "category": "vermittler", "country": "AT", "city": "Wien", "website": "https://www.tui.at", "size": "medium", "employees_approx": 350},
    {"name": "Hotelplan AG Reisebüro", "category": "vermittler", "country": "CH", "city": "Zürich", "website": "https://www.hotelplan.ch", "size": "medium", "employees_approx": 500},
    {"name": "Kiwi Tours AG", "category": "vermittler", "country": "CH", "city": "Bern", "website": "https://www.kiwitours.ch", "size": "small", "employees_approx": 90},
    {"name": "TCS Reisen AG", "category": "vermittler", "country": "CH", "city": "Emmen", "website": "https://www.tcs.ch/reisen", "size": "medium", "employees_approx": 220},

    # ═══ MIETWAGEN ═══
    {"name": "Buchbinder Autovermietung", "category": "mietwagen", "country": "DE", "city": "Wien", "website": "https://www.buchbinder.de", "phone_main": "+49 1806 99 22 11", "size": "medium", "employees_approx": 2200, "revenue_approx_eur": 280000000},
    {"name": "Interrent / Global Rent a Car", "category": "mietwagen", "country": "DE", "city": "Hamburg", "website": "https://www.interrent.com", "size": "medium", "employees_approx": 400},
    {"name": "Alamo Autovermietung", "category": "mietwagen", "country": "DE", "city": "Eschborn", "website": "https://www.alamo.de", "size": "medium", "employees_approx": 300},
    {"name": "National Car Rental Germany", "category": "mietwagen", "country": "DE", "city": "Eschborn", "website": "https://www.nationalcar.de", "size": "medium", "employees_approx": 280},
    {"name": "Starcar Autovermietung GmbH", "category": "mietwagen", "country": "DE", "city": "Hamburg", "website": "https://www.starcar.de", "phone_main": "+49 40 6077-0", "size": "medium", "employees_approx": 600, "revenue_approx_eur": 95000000},
    {"name": "Drivalia Mobility GmbH", "category": "mietwagen", "country": "DE", "city": "Frankfurt", "website": "https://www.drivalia.com", "size": "medium", "employees_approx": 350},
    {"name": "Flinkster GmbH (DB Rent)", "category": "mietwagen", "country": "DE", "city": "Frankfurt", "website": "https://www.flinkster.de", "size": "medium", "employees_approx": 180},
    {"name": "Miles Mobility GmbH", "category": "mietwagen", "country": "DE", "city": "Hamburg", "website": "https://www.miles-mobility.com", "size": "medium", "employees_approx": 260},
    {"name": "Sunny Cars GmbH", "category": "mietwagen", "country": "DE", "city": "München", "website": "https://www.sunnycars.de", "phone_main": "+49 89 500 35-0", "size": "medium", "employees_approx": 180, "revenue_approx_eur": 120000000},
    {"name": "DriveFlex GmbH", "category": "mietwagen", "country": "DE", "city": "Berlin", "website": "https://www.driveflex.com", "size": "small", "employees_approx": 75},
    {"name": "Mietwagen Zentrale AG", "category": "mietwagen", "country": "CH", "city": "Zürich", "website": "https://www.mietwagenzentrale.ch", "size": "small", "employees_approx": 60},
    {"name": "Europcar Austria GmbH", "category": "mietwagen", "country": "AT", "city": "Wien", "website": "https://www.europcar.at", "size": "medium", "employees_approx": 320},

    # ═══ HOTELKETTEN (mittelgroß) ═══
    {"name": "NH Hotel Group Germany", "category": "hotelkette", "country": "DE", "city": "Frankfurt", "website": "https://www.nh-hotels.de", "size": "large", "employees_approx": 1800, "revenue_approx_eur": 350000000},
    {"name": "Radisson Hotel Group Germany", "category": "hotelkette", "country": "DE", "city": "Berlin", "website": "https://www.radissonhotels.com", "size": "large", "employees_approx": 2200},
    {"name": "Hilton Hotels Germany", "category": "hotelkette", "country": "DE", "city": "Frankfurt", "website": "https://www.hilton.de", "size": "enterprise", "employees_approx": 3000},
    {"name": "Hyatt Hotels Germany", "category": "hotelkette", "country": "DE", "city": "Frankfurt", "website": "https://www.hyatt.com", "size": "large", "employees_approx": 1200},
    {"name": "InterContinental Hotels Germany", "category": "hotelkette", "country": "DE", "city": "Frankfurt", "website": "https://www.ihg.com", "size": "enterprise", "employees_approx": 2800},
    {"name": "Accor Hotels Germany", "category": "hotelkette", "country": "DE", "city": "Frankfurt", "website": "https://www.accor.com", "size": "enterprise", "employees_approx": 8000},
    {"name": "Wyndham Hotels Germany", "category": "hotelkette", "country": "DE", "city": "Frankfurt", "website": "https://www.wyndhamhotels.com", "size": "large", "employees_approx": 1500},
    {"name": "Best Western Hotels Germany", "category": "hotelkette", "country": "DE", "city": "Frankfurt", "website": "https://www.bestwestern.de", "phone_main": "+49 69 66640-0", "size": "medium", "employees_approx": 600, "revenue_approx_eur": 180000000},
    {"name": "B&B Hotels GmbH", "category": "hotelkette", "country": "DE", "city": "München", "website": "https://www.hotel-bb.com", "size": "large", "employees_approx": 3500, "revenue_approx_eur": 320000000},
    {"name": "Lindner Hotels AG", "category": "hotelkette", "country": "DE", "city": "Düsseldorf", "website": "https://www.lindner.de", "phone_main": "+49 211 6800-0", "size": "medium", "employees_approx": 2800, "revenue_approx_eur": 240000000},
    {"name": "Relexa Hotel GmbH", "category": "hotelkette", "country": "DE", "city": "Hannover", "website": "https://www.relexa-hotel.de", "size": "medium", "employees_approx": 900},
    {"name": "Ringhotels e.V.", "category": "hotelkette", "country": "DE", "city": "München", "website": "https://www.ringhotels.de", "size": "medium", "employees_approx": 500},
    {"name": "Kempinski Hotels Germany", "category": "hotelkette", "country": "DE", "city": "München", "website": "https://www.kempinski.com", "size": "large", "employees_approx": 1500},
    {"name": "Rocco Forte Hotels Germany", "category": "hotelkette", "country": "DE", "city": "München", "website": "https://www.roccofortehotels.com", "size": "medium", "employees_approx": 400},
    {"name": "Lotte Hotel Germany", "category": "hotelkette", "country": "DE", "city": "Berlin", "website": "https://www.lottehotel.com", "size": "medium", "employees_approx": 300},
    {"name": "Meininger Hotels GmbH", "category": "hotelkette", "country": "DE", "city": "Berlin", "website": "https://www.meininger-hotels.com", "phone_main": "+49 30 6663-6100", "size": "medium", "employees_approx": 1200, "revenue_approx_eur": 110000000},
    {"name": "Novum Hospitality GmbH", "category": "hotelkette", "country": "DE", "city": "Hamburg", "website": "https://www.novum-hotels.com", "size": "medium", "employees_approx": 1800, "revenue_approx_eur": 130000000},
    {"name": "Centro Hotel Group", "category": "hotelkette", "country": "DE", "city": "Hamburg", "website": "https://www.centro-hotels.de", "size": "medium", "employees_approx": 700},
    {"name": "Intercity Hotel GmbH", "category": "hotelkette", "country": "DE", "city": "Frankfurt", "website": "https://www.intercityhotel.com", "size": "medium", "employees_approx": 2000},
    {"name": "H-Hotels.com GmbH", "category": "hotelkette", "country": "DE", "city": "Bad Kissingen", "website": "https://www.h-hotels.com", "phone_main": "+49 971 7168-0", "size": "large", "employees_approx": 3200, "revenue_approx_eur": 190000000},
    {"name": "Achat Hotels GmbH", "category": "hotelkette", "country": "DE", "city": "Hockenheim", "website": "https://www.achat-hotels.com", "size": "medium", "employees_approx": 1100},
    {"name": "Dormero Hotels GmbH", "category": "hotelkette", "country": "DE", "city": "Stuttgart", "website": "https://www.dormero.de", "size": "medium", "employees_approx": 500},
    {"name": "Hyperion Hotels GmbH", "category": "hotelkette", "country": "DE", "city": "Frankfurt", "website": "https://www.hyperion-hotels.de", "size": "medium", "employees_approx": 700},
    {"name": "Ruby Hotels GmbH", "category": "hotelkette", "country": "DE", "city": "München", "website": "https://www.ruby-hotels.com", "size": "medium", "employees_approx": 600},
    {"name": "25hours Hotel Company GmbH", "category": "hotelkette", "country": "DE", "city": "Hamburg", "website": "https://www.25hours-hotels.com", "size": "medium", "employees_approx": 800},
    {"name": "Precise Hotels & Resorts", "category": "hotelkette", "country": "DE", "city": "Berlin", "website": "https://www.precise-hotels.com", "size": "medium", "employees_approx": 1500},
    {"name": "Swissôtel Deutschland", "category": "hotelkette", "country": "DE", "city": "Berlin", "website": "https://www.swissotel.com", "size": "medium", "employees_approx": 400},
    {"name": "Mandarin Oriental Germany", "category": "hotelkette", "country": "DE", "city": "München", "website": "https://www.mandarinoriental.com", "size": "medium", "employees_approx": 350},
    {"name": "Austria Trend Hotels", "category": "hotelkette", "country": "AT", "city": "Wien", "website": "https://www.austria-trend.at", "phone_main": "+43 1 58800-0", "size": "medium", "employees_approx": 1800, "revenue_approx_eur": 160000000},
    {"name": "Sacher Hotels GmbH", "category": "hotelkette", "country": "AT", "city": "Wien", "website": "https://www.sacher.com", "size": "medium", "employees_approx": 600},
    {"name": "Motel One Austria GmbH", "category": "hotelkette", "country": "AT", "city": "Wien", "website": "https://www.motel-one.com", "size": "medium", "employees_approx": 400},
    {"name": "Schindler Hotels GmbH", "category": "hotelkette", "country": "AT", "city": "Innsbruck", "website": "https://www.schindlerhotels.com", "size": "small", "employees_approx": 180},
    {"name": "Warema Hotels AG", "category": "hotelkette", "country": "CH", "city": "Zürich", "website": "https://www.warema.ch", "size": "small", "employees_approx": 120},
    {"name": "Swiss Hotel Properties AG", "category": "hotelkette", "country": "CH", "city": "Zürich", "website": "https://www.shp.ch", "size": "medium", "employees_approx": 800},
    {"name": "Sorell Hotels AG", "category": "hotelkette", "country": "CH", "city": "Zürich", "website": "https://www.sorellhotels.com", "size": "medium", "employees_approx": 700},

    # ═══ DMC / INCOMING ═══
    {"name": "Incoming Germany GmbH", "category": "dmc", "country": "DE", "city": "Berlin", "website": "https://www.incoming-germany.de", "size": "small", "employees_approx": 80},
    {"name": "Bavaria Incoming GmbH", "category": "dmc", "country": "DE", "city": "München", "website": "https://www.bavaria-incoming.de", "size": "small", "employees_approx": 65},
    {"name": "Alpine Incoming GmbH", "category": "dmc", "country": "AT", "city": "Innsbruck", "website": "https://www.alpine-incoming.at", "size": "small", "employees_approx": 55},
    {"name": "Aviareps AG", "category": "dmc", "country": "DE", "city": "München", "website": "https://www.aviareps.com", "phone_main": "+49 89 55 27 97-0", "size": "medium", "employees_approx": 650, "revenue_approx_eur": 75000000},
    {"name": "BCD Travel Germany GmbH", "category": "dmc", "country": "DE", "city": "Frankfurt", "website": "https://www.bcdtravel.de", "size": "large", "employees_approx": 1200, "revenue_approx_eur": 400000000},
    {"name": "American Express Global Business Travel", "category": "dmc", "country": "DE", "city": "Frankfurt", "website": "https://www.amexglobalbusinesstravel.com", "size": "enterprise", "employees_approx": 800},
    {"name": "CWT Germany GmbH", "category": "dmc", "country": "DE", "city": "Frankfurt", "website": "https://www.mycwt.com", "size": "large", "employees_approx": 600},
    {"name": "Egencia GmbH", "category": "dmc", "country": "DE", "city": "Berlin", "website": "https://www.egencia.de", "size": "medium", "employees_approx": 280},
    {"name": "Kofler & Kompanie Event GmbH", "category": "dmc", "country": "DE", "city": "München", "website": "https://www.kofler-kompanie.com", "size": "medium", "employees_approx": 300},

    # ═══ ACTIVITY PROVIDER / ERLEBNISSE ═══
    {"name": "Jochen Schweizer GmbH", "category": "activity_provider", "country": "DE", "city": "München", "website": "https://www.jochen-schweizer.de", "phone_main": "+49 89 24 24 09-0", "size": "medium", "employees_approx": 450, "revenue_approx_eur": 110000000},
    {"name": "mydays GmbH", "category": "activity_provider", "country": "DE", "city": "München", "website": "https://www.mydays.de", "size": "medium", "employees_approx": 200},
    {"name": "Erlebnisgeschenke.de GmbH", "category": "activity_provider", "country": "DE", "city": "Düsseldorf", "website": "https://www.erlebnisgeschenke.de", "size": "small", "employees_approx": 85},
    {"name": "Eurail Group GmbH", "category": "activity_provider", "country": "DE", "city": "Frankfurt", "website": "https://www.eurail.com", "size": "medium", "employees_approx": 180},
    {"name": "Interrail / Rail Europe Germany", "category": "activity_provider", "country": "DE", "city": "Frankfurt", "website": "https://www.raileurope.com", "size": "medium", "employees_approx": 150},
    {"name": "Tiqets Germany GmbH", "category": "activity_provider", "country": "DE", "city": "Berlin", "website": "https://www.tiqets.com", "size": "medium", "employees_approx": 160},
    {"name": "Viator Germany GmbH", "category": "activity_provider", "country": "DE", "city": "Berlin", "website": "https://www.viator.com", "size": "medium", "employees_approx": 120},

    # ═══ REISEVERSICHERUNG ═══
    {"name": "ERGO Reiseversicherung AG", "category": "versicherung", "country": "DE", "city": "München", "website": "https://www.ergo-reiseversicherung.de", "phone_main": "+49 89 4166-1234", "size": "large", "employees_approx": 900, "revenue_approx_eur": 280000000},
    {"name": "Allianz Global Assistance Germany", "category": "versicherung", "country": "DE", "city": "München", "website": "https://www.allianz-assistance.de", "size": "large", "employees_approx": 1200, "revenue_approx_eur": 350000000},
    {"name": "HanseMerkur Reiseversicherung AG", "category": "versicherung", "country": "DE", "city": "Hamburg", "website": "https://www.hansemerkur.de", "phone_main": "+49 40 4119-2200", "size": "medium", "employees_approx": 700, "revenue_approx_eur": 220000000},
    {"name": "Europäische Reiseversicherung AG", "category": "versicherung", "country": "DE", "city": "München", "website": "https://www.europaeische.de", "size": "medium", "employees_approx": 500},
    {"name": "AXA Travel Insurance Germany", "category": "versicherung", "country": "DE", "city": "Köln", "website": "https://www.axa.de/reiseversicherung", "size": "large", "employees_approx": 800},
    {"name": "Würzburger Versicherungs-AG (Reise)", "category": "versicherung", "country": "DE", "city": "Würzburg", "website": "https://www.wuerzburger.com", "size": "medium", "employees_approx": 350},
    {"name": "Generali Versicherung (Reise)", "category": "versicherung", "country": "AT", "city": "Wien", "website": "https://www.generali.at", "size": "large", "employees_approx": 600},

    # ═══ TRAVEL TECH / GDS ═══
    {"name": "Travelport Germany GmbH", "category": "tech_provider", "country": "DE", "city": "Frankfurt", "website": "https://www.travelport.com", "size": "large", "employees_approx": 400},
    {"name": "Farelogix Germany GmbH", "category": "tech_provider", "country": "DE", "city": "Frankfurt", "website": "https://www.farelogix.com", "size": "medium", "employees_approx": 150},
    {"name": "IBS Software Germany", "category": "tech_provider", "country": "DE", "city": "Frankfurt", "website": "https://www.ibsplc.com", "size": "medium", "employees_approx": 200},
    {"name": "Derpart Travel Service GmbH", "category": "tech_provider", "country": "DE", "city": "Frankfurt", "website": "https://www.derpart.com", "size": "medium", "employees_approx": 250},
    {"name": "Comforta GmbH", "category": "tech_provider", "country": "DE", "city": "Hamburg", "website": "https://www.comforta.de", "size": "small", "employees_approx": 90},
    {"name": "Netmatch GmbH", "category": "tech_provider", "country": "DE", "city": "Hamburg", "website": "https://www.netmatch.de", "size": "small", "employees_approx": 70},
    {"name": "Tourism Infrastructure International", "category": "tech_provider", "country": "DE", "city": "München", "website": "https://www.tii.de", "size": "small", "employees_approx": 60},

    # ═══ BAHN / TRANSFER ═══
    {"name": "Deutsche Bahn Fernverkehr AG", "category": "bahn", "country": "DE", "city": "Frankfurt", "website": "https://www.bahn.de", "phone_main": "+49 30 2970", "size": "enterprise", "employees_approx": 33000, "revenue_approx_eur": 4500000000},
    {"name": "ÖBB Personenverkehr AG", "category": "bahn", "country": "AT", "city": "Wien", "website": "https://www.oebb.at", "phone_main": "+43 5 1717", "size": "enterprise", "employees_approx": 24000, "revenue_approx_eur": 2100000000},
    {"name": "SBB AG Personenverkehr", "category": "bahn", "country": "CH", "city": "Bern", "website": "https://www.sbb.ch", "size": "enterprise", "employees_approx": 33000, "revenue_approx_eur": 3900000000},
    {"name": "FlixBus GmbH", "category": "bus_coach", "country": "DE", "city": "München", "website": "https://www.flixbus.de", "phone_main": "+49 30 300 137 300", "size": "enterprise", "employees_approx": 2500, "revenue_approx_eur": 1200000000},
    {"name": "Flix SE", "category": "bus_coach", "country": "DE", "city": "München", "website": "https://www.flixbus.com", "size": "large", "employees_approx": 1800},
    {"name": "BerlinLinienBus GmbH", "category": "bus_coach", "country": "DE", "city": "Berlin", "website": "https://www.berlinlinienbus.de", "size": "medium", "employees_approx": 200},
    {"name": "Europabus GmbH", "category": "bus_coach", "country": "DE", "city": "Frankfurt", "website": "https://www.europabus.de", "size": "medium", "employees_approx": 180},
    {"name": "Ruf Reisen GmbH", "category": "bus_coach", "country": "DE", "city": "Nürnberg", "website": "https://www.ruf-reisen.de", "size": "medium", "employees_approx": 250, "revenue_approx_eur": 85000000},
    {"name": "Ikarus Bus GmbH", "category": "bus_coach", "country": "DE", "city": "Neu-Ulm", "website": "https://www.ikarus.de", "size": "medium", "employees_approx": 160},
    {"name": "Dr. Richard Regionalbus GmbH", "category": "bus_coach", "country": "AT", "city": "Wien", "website": "https://www.drrichard.at", "size": "medium", "employees_approx": 1200},
]

# Gesamt: ~200 zusätzliche Unternehmen
print(f"Erweiterter Seed: {len(EXTENDED_COMPANIES)} Unternehmen")
