-- Taxonomie Punkt 3, SCHRITT B: employees_masked Spaltenmaskierung aufs Modell (Achse 'columns').
-- NUR der Masking-CASE wird ersetzt; Zeilenfilter (perm_proj_ok, Schritt-5-Teil-B) + ELSE-Whitelist (operativ)
-- + View-Optionen bleiben bit-genau. Reproduziert IST: voll+salary=all → alles (mgmt/finance); voll ohne
-- salary-Clearance → alles außer GF-Schutz (hr, is_protected_employee bleibt); personal → alles außer Gehalt
-- (künftig); operativ → Betriebs-Whitelist (Leads). Gehalt zusätzlich über die Gehalt-Achse (salary=all).

create or replace view public.employees_masked with (security_invoker=false, security_barrier=true) as
 SELECT r.id,
    r.first_name,
    r.last_name,
    r.email,
    r.phone,
    r.staff_number,
    r.role_keys,
    r.project_id,
    r.skill,
    r.target_role,
    r.status,
    r.source,
    r.cv_skills,
    r.hire_date,
    r.termination_date,
    r.location,
    r.photo_url,
    r.about_text,
    r.interests,
    r.notes,
    r.salary_type,
    r.hourly_rate,
    r.work_model,
    r.work_hours,
    r.shift_earliest,
    r.shift_latest,
    r.vacation_days,
    r.absences,
    r.audios,
    r.videos,
    r.warnings,
    r.project_assignments,
    r.allowed_shifts,
    r.bank,
    r.contract,
    r.extra,
    r.created_at,
    r.updated_at,
    r.abilities,
    r.bonuses,
    r.referrals,
    r.quality_ratings,
    r.hardware,
    r."position",
    r.city,
    r.id_number,
    r.project_skill,
    r.primary_skill,
    r.photo_color,
    r.fixed_salary,
    r.guaranteed_pct,
    r.deduct_missing,
    r.free_days_month,
    r.overtime_allowed,
    r.productive_pct,
    r.forecast_include,
    r.efficiency_override_pct,
    r.age,
    r.gender,
    r.education,
    r.education_level,
    r.experience_years,
    r.language_level,
    r.writing_level,
    r.languages_str,
    r.dream,
    r.hobbies,
    r.favorite_food,
    r.travel_wish,
    r.birthday,
    r.work_holidays,
    r.work_saturday,
    r.work_sunday,
    r.work_split,
    r.work_notes,
    r.training_id,
    r.staff_number_old,
    r.import_source,
    r.kpi_exempt,
    r.overhead_productive_pct,
    r.email_internal,
    r.salary_currency,
    r.status_changed_at
   FROM ( SELECT e_1.id,
            e_1.first_name,
            e_1.last_name,
            e_1.email,
            e_1.phone,
            e_1.staff_number,
            e_1.role_keys,
            e_1.project_id,
            e_1.skill,
            e_1.target_role,
            e_1.status,
            e_1.source,
            e_1.cv_skills,
            e_1.hire_date,
            e_1.termination_date,
            e_1.location,
            e_1.photo_url,
            e_1.about_text,
            e_1.interests,
            e_1.notes,
            e_1.salary_type,
            e_1.hourly_rate,
            e_1.work_model,
            e_1.work_hours,
            e_1.shift_earliest,
            e_1.shift_latest,
            e_1.vacation_days,
            e_1.absences,
            e_1.audios,
            e_1.videos,
            e_1.warnings,
            e_1.project_assignments,
            e_1.allowed_shifts,
            e_1.bank,
            e_1.contract,
            e_1.extra,
            e_1.created_at,
            e_1.updated_at,
            e_1.abilities,
            e_1.bonuses,
            e_1.referrals,
            e_1.quality_ratings,
            e_1.hardware,
            e_1."position",
            e_1.city,
            e_1.id_number,
            e_1.project_skill,
            e_1.primary_skill,
            e_1.photo_color,
            e_1.fixed_salary,
            e_1.guaranteed_pct,
            e_1.deduct_missing,
            e_1.free_days_month,
            e_1.overtime_allowed,
            e_1.productive_pct,
            e_1.forecast_include,
            e_1.efficiency_override_pct,
            e_1.age,
            e_1.gender,
            e_1.education,
            e_1.education_level,
            e_1.experience_years,
            e_1.language_level,
            e_1.writing_level,
            e_1.languages_str,
            e_1.dream,
            e_1.hobbies,
            e_1.favorite_food,
            e_1.travel_wish,
            e_1.birthday,
            e_1.work_holidays,
            e_1.work_saturday,
            e_1.work_sunday,
            e_1.work_split,
            e_1.work_notes,
            e_1.training_id,
            e_1.staff_number_old,
            e_1.import_source,
            e_1.kpi_exempt,
            e_1.overhead_productive_pct,
            e_1.email_internal,
            e_1.salary_currency,
            e_1.status_changed_at
           FROM employees e_1
          WHERE perm_mode(auth.uid(), 'emp'::text) <> 'none'::text AND perm_proj_ok(auth.uid(), 'emp'::text, e_1.project_id, NULL::text) AND (perm_allowed_projects(auth.uid(), 'emp'::text) IS NULL OR (e_1.status = ANY (ARRAY['active'::text, 'training'::text])))) e
     CROSS JOIN LATERAL ( SELECT
                CASE
                    WHEN (public.perm(auth.uid(), 'emp'::text) ->> 'columns') = 'voll' AND (public.perm(auth.uid(), 'emp'::text) ->> 'salary') = 'all' THEN to_jsonb(e.*)
                    WHEN (public.perm(auth.uid(), 'emp'::text) ->> 'columns') = 'voll' THEN
                    CASE
                        WHEN is_protected_employee(e.id) THEN to_jsonb(e.*) - 'fixed_salary'::text - 'hourly_rate'::text - 'salary_currency'::text - 'bank'::text - 'contract'::text - 'id_number'::text
                        ELSE to_jsonb(e.*)
                    END
                    WHEN (public.perm(auth.uid(), 'emp'::text) ->> 'columns') = 'personal' THEN to_jsonb(e.*) - 'fixed_salary'::text - 'hourly_rate'::text - 'salary_currency'::text
                    ELSE jsonb_build_object('contract', jsonb_build_object('start', (to_jsonb(e.*) -> 'contract'::text) -> 'start'::text), 'writing_level', to_jsonb(e.*) -> 'writing_level'::text, 'languages_str', to_jsonb(e.*) -> 'languages_str'::text, 'target_role', to_jsonb(e.*) -> 'target_role'::text, 'cv_skills', to_jsonb(e.*) -> 'cv_skills'::text, 'education', to_jsonb(e.*) -> 'education'::text, 'education_level', to_jsonb(e.*) -> 'education_level'::text, 'experience_years', to_jsonb(e.*) -> 'experience_years'::text, 'quality_ratings', to_jsonb(e.*) -> 'quality_ratings'::text, 'hire_date', to_jsonb(e.*) -> 'hire_date'::text, 'termination_date', to_jsonb(e.*) -> 'termination_date'::text, 'project_assignments', to_jsonb(e.*) -> 'project_assignments'::text, 'id', to_jsonb(e.*) -> 'id'::text, 'first_name', to_jsonb(e.*) -> 'first_name'::text, 'last_name', to_jsonb(e.*) -> 'last_name'::text, 'position', to_jsonb(e.*) -> 'position'::text, 'status', to_jsonb(e.*) -> 'status'::text, 'project_id', to_jsonb(e.*) -> 'project_id'::text, 'role_keys', to_jsonb(e.*) -> 'role_keys'::text, 'photo_url', to_jsonb(e.*) -> 'photo_url'::text, 'photo_color', to_jsonb(e.*) -> 'photo_color'::text, 'email', to_jsonb(e.*) -> 'email'::text, 'email_internal', to_jsonb(e.*) -> 'email_internal'::text, 'phone', to_jsonb(e.*) -> 'phone'::text, 'city', to_jsonb(e.*) -> 'city'::text, 'location', to_jsonb(e.*) -> 'location'::text, 'language_level', to_jsonb(e.*) -> 'language_level'::text, 'skill', to_jsonb(e.*) -> 'skill'::text, 'project_skill', to_jsonb(e.*) -> 'project_skill'::text, 'primary_skill', to_jsonb(e.*) -> 'primary_skill'::text, 'work_hours', to_jsonb(e.*) -> 'work_hours'::text, 'work_model', to_jsonb(e.*) -> 'work_model'::text, 'shift_earliest', to_jsonb(e.*) -> 'shift_earliest'::text, 'shift_latest', to_jsonb(e.*) -> 'shift_latest'::text, 'allowed_shifts', to_jsonb(e.*) -> 'allowed_shifts'::text, 'work_saturday', to_jsonb(e.*) -> 'work_saturday'::text, 'work_sunday', to_jsonb(e.*) -> 'work_sunday'::text, 'work_holidays', to_jsonb(e.*) -> 'work_holidays'::text, 'work_weekend', to_jsonb(e.*) -> 'work_weekend'::text, 'work_split', to_jsonb(e.*) -> 'work_split'::text, 'absences', to_jsonb(e.*) -> 'absences'::text, 'vacation_days', to_jsonb(e.*) -> 'vacation_days'::text, 'kpi_exempt', to_jsonb(e.*) -> 'kpi_exempt'::text, 'created_at', to_jsonb(e.*) -> 'created_at'::text)
                END AS j) m
     CROSS JOIN LATERAL jsonb_populate_record(NULL::employees, m.j) r(id, first_name, last_name, email, phone, staff_number, role_keys, project_id, skill, target_role, status, source, cv_skills, hire_date, termination_date, location, photo_url, about_text, interests, notes, salary_type, hourly_rate, work_model, work_hours, shift_earliest, shift_latest, vacation_days, absences, audios, videos, warnings, project_assignments, allowed_shifts, bank, contract, extra, created_at, updated_at, abilities, bonuses, referrals, quality_ratings, hardware, "position", city, id_number, project_skill, primary_skill, photo_color, fixed_salary, guaranteed_pct, deduct_missing, free_days_month, overtime_allowed, productive_pct, forecast_include, efficiency_override_pct, age, gender, education, education_level, experience_years, language_level, writing_level, languages_str, dream, hobbies, favorite_food, travel_wish, birthday, work_holidays, work_saturday, work_sunday, work_split, work_notes, training_id, staff_number_old, import_source, kpi_exempt, overhead_productive_pct, email_internal, salary_currency, status_changed_at);;

-- ROLLBACK: employees_masked mit dem alten Masking-CASE (is_management/is_finance/is_hr/ELSE) neu erstellen
-- (siehe git: migrations/2026-08-30_rls_emp_B_maskedview.sql-Stand bzw. voriger pg_get_viewdef-Dump).
